### ISSUE TITLE
Interface för projekt

### ISSUE THREAD

**Issue by sunnanv** [SAAB2017/3PP-tool#10]
(Se lista, lägga till)

**Comment by sunnanv** [comment]
Kommer använda ProjectsList och index.js

**Comment by Poremski** [comment]
Jag anser att denna implementering bör ske separat ifrån varandra i den bemärkelse att de olika avsvaren (list och add) ger användarbarhet och det råder störe risk för otydlighet och risk för felaktig navigering.
