### ISSUE TITLE
Datum läggs in med olika format beroende på dator

### ISSUE THREAD

**Issue by sunnanv** [SAAB2017/3PP-tool#117]
Datum läggs in som olika format beroende på vilken dator man är på. Kommer ihåg att Simon sa att det läggs in/hämtas ut med "locale" någonting. Skulle varit bättre om det hämtades på ett standard-sätt (t ex 2017-10-15)

**Comment by sunnanv** [comment]
Märkte att det antagligen bara är när man lägger till/visar produkter. Det andra ger formatet ÅÅÅÅ-MM-DD

**Comment by theIDinside** [comment]
Löst as of #124 

Alla datum läggs nu in med toLocaleDateString() istället, som ger ett bättre format (2015-01-23 t.ex.)
