### ISSUE TITLE
Samma komponent visas mer än en gång i detaljvyn över ett givet projekt

### ISSUE THREAD

**Issue by Poremski** [SAAB2017/3PP-tool#150]
## Beskrivning av bugg
I detaljvyn över ett givet projekt visas komponenter fler endast en gång.

## Krav för att uppnå buggen
- Projektet har minst två produkter.
- Minst två produter som tillhör berörd projekt har en eller flera komponenter av exakt samma typ.

## Förväntad resultat
En komponent av samam typ ska visas endast en gång.

## Skrämdump
<img width="1176" alt="captura de pantalla 2017-11-21 a las 16 14 10" src="https://user-images.githubusercontent.com/13387829/33090445-4b22fae0-cef4-11e7-9742-66bbb6128ad3.png">

**Comment by theIDinside** [comment]
Än så länge fixade:

- [x] components.js
- [x] products.js
- [x] projects.js

**Comment by theIDinside** [comment]
Solved as of #152
