### ISSUE TITLE
Table in Overview.vue not taking up full width of parent

### ISSUE THREAD

**Issue by Poremski** [SAAB2017/3PP-tool#16]
Filen _src/views/Overview.vue_ innehåller en tabell vars bredd inte tar upp 100 % av förälderns bredd. Detta medför att tabellens body-container utnyttjas inte till fullo.
För att lösa problemet bör man kanske ta bort "is-3" i CSS-klassdeklareringen?

**Comment by sunnanv** [comment]
Har löst responsiveness men får inte till att den centreras när den kollapsar. Ska jobba vidare på detta!

**Comment by Poremski** [comment]
Hur går det?
