### ISSUE TITLE
Interface för godkännande av projekt

### ISSUE THREAD

**Issue by theIDinside** [SAAB2017/3PP-tool#18]
Är osäker på vad som ska va med. Påbörjar dock nåt

**Comment by Poremski** [comment]
@theIDinside Har du fått klarhet i vad som ska vara med?

**Comment by theIDinside** [comment]
@Poremski, @sunnanv . @MarkusSkarhammar , @dat15dmi 
Inte direkt. Frågan är ifall den här funktionen ens skall finnas med? Som Pierre sa på sista mötet, det är licenser som skall kopplas till komponenter. Troligtvis bör det vara där själva godkännandet sker. Men å andra sidan, basic sidan vi fick, hade ju med "Pending Projects" .... eller?
