### ISSUE TITLE
Realtidsuppdateringskonflikt

### ISSUE THREAD

**Issue by Poremski** [SAAB2017/3PP-tool#21]
Problem med realtidsuppdatering av hemsidan vid navigering via webbläsaren. Efter att ha gått in på en sida utöver startsidan, reagerar inte realtidsuppdateringen av sidan när man begär åtkomst till en annan sida.

**Följande steg för att upprepa bugg:**
1. Gå in på hemsidan
2. Tryck på "list projects"
3. Var på uppmärksam på att det inte går att gå in på någon annan sida efter punkt 2 utan att aktivt uppdatera hemsidan (F5).

**Comment by sunnanv** [comment]
Detta problem uppstår inte längre, ska vi stänga issue?

**Comment by Poremski** [comment]
Detta issue har uppståt i samband med när routningen ändrades till historisk navigering, dvs. när man hade localhost:8080/#/ vilket ändrades till localhost:8080/. Eftersom länkarna var statiska i menyn, så uppdaterades inte dem i samband med förändringen och refererade då till ./# vilket gav okorrekt förfrågan till routningen. Detta har åtgärdats under sprint 1 och därmed kan detta issue stängas.
