### ISSUE TITLE
Överskrivning av signering

### ISSUE THREAD

**Issue by Poremski** [SAAB2017/3PP-tool#39]
När två användare ska signera ett och samma objekt och går in på sidan för signering, kommer enkeltrådighet i backend medföra att första användarens signering läggs in varpå den andra användarens signering skriver över den första användarens signering.

Detta är nåt som strider mot kraven då det ska vara möjlighet med fler än en användare - samt att signering inte får överskrivas.

En kontroll behövs som säkerställer att den signerande komponenten inte redan är signerad - och att ett specifikt fel returneras som kan plockas upp av frontend som kommunicerar felmeddelandet till användare två, typ "Komponenten du försöker signera har precis blivit signerad av en annan användare" eller "Komponenten du försöker signera har precis blivit signerad en 'xxxx'" den "dd-mm-yy" kl "hh:mm:ss" - beroende på vad vi väljer att returnera för felinformation.

Ett exempel på hur ett JSON-respons kan se ut för ett fel som kan vara användbart av front-end:
```json
{
     "errorType": "alreadySigned", 
     "byUser": "xxxx", 
     "onTime": "1510062744"
}
```

**Comment by MarkusSkarhammar** [comment]
Det ska nu vara fixat. Det är inte möjligt att ersätta en signerad komponent med en annan signering och om det försöks skickas ett meddelande enligt beskrivningen ovan.
