### ISSUE TITLE
Backend kraschar när man går in på specifik licens/komponent/produkt/projekt

### ISSUE THREAD

**Issue by sunnanv** [SAAB2017/3PP-tool#57]
Om man går in på en sida för en licens (trycker på licensen i listan) så kraschar backend. Detta gäller även komponent, produkt och projekt.

![skarmavbild 2017-11-08 kl 12 36 06](https://user-images.githubusercontent.com/25319966/32547119-71d16dd4-c481-11e7-8488-7a85d2c3810f.png)

**Comment by MarkusSkarhammar** [comment]
Detta ska nu vara fixat.
