### ISSUE TITLE
Interface för produkter

### ISSUE THREAD

**Issue by sunnanv** [SAAB2017/3PP-tool#7]
(Se lista, lägga till)

**Comment by sunnanv** [comment]
Använder ProductsList och liten ändring i index.js

**Comment by Poremski** [comment]
Jag anser att denna implementering bör ske separat ifrån varandra i den bemärkelse att de olika avsvaren (list och add) ger användarbarhet och det råder störe risk för otydlighet och risk för felaktig navigering.
