### ISSUE TITLE
Överlappning av tabeller

### ISSUE THREAD

**Issue by Poremski** [SAAB2017/3PP-tool#87]
Tabellerna överlappar varandra, se skärmdumpen nedan:
<img width="1024" alt="captura de pantalla 2017-11-14 a las 12 13 17" src="https://user-images.githubusercontent.com/13387829/32777197-830bd482-c935-11e7-8d95-9c2134e2f55e.png">

Tabellerna verkar vara statiska och icke rörbara vid skärmbredsförändring. Kollapsningen sker också något för sent med avseende på tabellens bredd.

Problemet uppstår vid bredden 1023 px < 1367 px. Probelmet drabbar på så vis följande skärmar:
- XGA (1024x768)
- XGA+ (1152x864)
- QVGA (1280x960)
- SXGA (1280x1024)
- HD / WXGA (1280x720; 1280x800)
- HD / FWXGA (1366x768)

Enligt [W3Schools](https://www.w3schools.com/browsers/browsers_display.asp) skulle probelemet ovan beröra 47 % av internetanvändare år 2017 (räknat på den skärmupplösning som är aktuell under 2017).

**Comment by sunnanv** [comment]
![skarmavbild 2017-11-14 kl 20 19 11](https://user-images.githubusercontent.com/25319966/32799987-7b00ad96-c979-11e7-8432-2f3fa33fb4f3.png)

Blir det bättre med en overview i den här stilen? Då kommer vi även ha med licenses som vi inte har haft med innan. 

Såhär ser det ut precis innan kollaps:
![skarmavbild 2017-11-14 kl 20 22 57](https://user-images.githubusercontent.com/25319966/32800044-a70e6586-c979-11e7-90e4-abccfbd56c21.png)

Och övergår till:
![skarmavbild 2017-11-14 kl 20 23 50](https://user-images.githubusercontent.com/25319966/32800125-d1065cf4-c979-11e7-9257-05cf1999c2ad.png)

och slutligen:
![skarmavbild 2017-11-14 kl 20 24 02](https://user-images.githubusercontent.com/25319966/32800138-d8e6f3c0-c979-11e7-886f-f77115884fdb.png)
